function archs = downsample_archs(archs, nmf_log2_oversampling)
archs{2}.banks{1}.behavior.S.log2_oversampling = ...
    nmf_log2_oversampling;
archs{2}.invariants{1}.behavior.S.log2_oversampling = ...
    nmf_log2_oversampling;
archs{3}.invariants{1}.behavior.S.log2_oversampling = ...
    nmf_log2_oversampling;
end